<?php

$messages['api_error_contact_admin'] = 'Ocorreu um erro ao gerar o e-mail. Por favor, entre em contato com o administrador.';

$messages['ai_no_instructions'] = 'Digite as instruções';
$messages['ai_instructions_too_long'] = 'Suas instruções são muito longas; elas podem ter no máximo $n caracteres.';
$messages['ai_empty_response'] = 'O servidor retornou uma resposta vazia';

$messages['ai_validation_error_not_enough_characters_instruction'] = 'O número de caracteres deve ser maior que 1!';
$messages['ai_validation_error_invalid_input_instructions'] = 'O campo "instruções" deve conter um texto válido!';
$messages['ai_validation_error_invalid_input_subject'] = 'O campo "assunto" deve conter um texto válido.';
$messages['ai_validation_error_invalid_recipient_email_address'] = 'O endereço de e-mail do destinatário é inválido.';
$messages['ai_validation_error_invalid_sender_email_address'] = 'O endereço de e-mail do remetente é inválido.';
$messages['ai_validation_error_invalid_style'] = 'O campo "estilo" é inválido!';
$messages['ai_validation_error_invalid_language'] = 'O campo "idioma" é inválido!';
$messages['ai_validation_error_invalid_length'] = 'O campo "tamanho" é inválido!';
$messages['ai_validation_error_invalid_creativity'] = 'O campo "criatividade" é inválido!';
$messages['ai_validation_error_sender_name_mandatory'] = 'O nome do remetente é obrigatório!';
$messages['ai_validation_error_invalid_sender_name_text'] = 'O campo "Nome do Remetente" deve conter um texto válido!';
$messages['ai_validation_error_invalid_recipient_name_text'] = 'O campo "Nome do Destinatário" deve conter um texto válido!';
$messages['ai_validation_error_not_enough_characters_sender_name'] = 'O campo "Nome do Remetente" deve ter pelo menos 3 caracteres.';
$messages['ai_validation_error_not_enough_characters_recipient_name'] = 'O campo "Nome do Destinatário" deve ter pelo menos 3 caracteres, caso seja preenchido.';

$messages['ai_predefined_request_error'] = 'Ocorreu um erro ao processar a solicitação.';
$messages['ai_predefined_delete_error'] = 'Ocorreu um erro ao excluir a instrução.';
$messages['ai_predefined_get_all_instructions_error'] = 'Ocorreu um erro ao buscar as instruções.';
$messages['ai_predefined_get_specific_instruction_error'] = 'Ocorreu um erro ao buscar informações da instrução.';
$messages['ai_predefined_content_error'] = 'Erro ao exibir a página.';
$messages['ai_predefined_max_instructions_error'] = 'O número máximo de instruções disponíveis é 20!';
